DROP TABLE IF EXISTS pet;

CREATE TABLE IF NOT EXISTS pet (
	id_pet INT NOT NULL PRIMARY KEY,
	name TEXT NOT NULL,
	type VARCHAR(3) ENUM("cat", "dog"),
	race VARCHAR(50),
	createdAt DATE NOT NULL
);
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (1, 'consectetuer', 'cat', 'Vira Lata', '2021/11/21');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (2, 'vulputate', 'dog', 'Chihuahua', '2022/06/01');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (3, 'aliquet', 'cat', 'Raggamuffin', '2022/06/14');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (4, 'lectus', 'dog', 'Poodle', '2022/06/20');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (5, 'morbi', 'cat', 'Ragdoll', '2022/07/21');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (6, 'tristique', 'cat', 'Raggamuffin', '2022/05/17');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (7, 'quisque', 'dog', 'Poodle', '2022/03/17');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (8, 'faucibus', 'dog', 'Vira Lata', '2021/10/08');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (9, 'sit', 'dog', 'Labrador', '2022/05/01');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (10, 'mi', 'cat', 'Ragdoll', '2022/01/05');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (11, 'varius', 'dog', 'Dachshund', '2022/01/02');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (12, 'erat', 'cat', 'Raggamuffin', '2022/01/15');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (13, 'est', 'dog', 'Akita', '2021/11/08');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (14, 'mauris', 'cat', 'Persa', '2022/06/17');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (15, 'morbi', 'dog', 'Vira Lata', '2021/12/15');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (16, 'mauris', 'dog', 'Poodle', '2022/03/05');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (17, 'felis', 'cat', 'Persa', '2021/12/31');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (18, 'vel', 'cat', 'Red Point', '2021/12/08');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (19, 'in', 'cat', 'Siames', '2022/06/02');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (20, 'ultrices', 'dog', 'Labrador', '2022/02/24');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (21, 'sit', 'dog', 'Vira Lata', '2021/10/07');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (22, 'cum', 'dog', 'Labrador', '2022/03/11');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (23, 'ac', 'cat', 'Red Point', '2022/04/16');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (24, 'vel', 'dog', 'Dachshund', '2022/02/13');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (25, 'eleifend', 'cat', 'Red Point', '2021/12/13');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (26, 'natoque', 'cat', 'Ragdoll', '2021/12/28');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (27, 'orci', 'cat', 'Raggamuffin', '2022/05/02');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (28, 'ultrices', 'dog', 'Vira Lata', '2022/08/14');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (29, 'blandit', 'cat', 'Raggamuffin', '2022/02/08');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (30, 'elementum', 'dog', 'Dachshund', '2021/11/26');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (31, 'volutpat', 'dog', 'Labrador', '2022/08/16');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (32, 'pretium', 'cat', 'Siames', '2022/06/10');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (33, 'tortor', 'cat', 'Red Point', '2022/02/15');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (34, 'nibh', 'cat', 'Red Point', '2022/03/02');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (35, 'sapien', 'cat', 'Ragdoll', '2021/09/12');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (36, 'sollicitudin', 'dog', 'Chihuahua', '2022/05/06');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (37, 'a', 'dog', 'Labrador', '2021/12/27');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (38, 'vestibulum', 'dog', 'Chihuahua', '2021/12/24');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (39, 'ut', 'cat', 'Persa', '2022/05/10');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (40, 'mi', 'dog', 'Akita', '2022/01/04');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (41, 'interdum', 'cat', 'Red Point', '2022/07/04');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (42, 'pellentesque', 'dog', 'Dachshund', '2022/02/05');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (43, 'ut', 'dog', 'Chihuahua', '2021/11/29');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (44, 'ante', 'cat', 'Red Point', '2021/10/16');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (45, 'faucibus', 'cat', 'Red Point', '2022/04/14');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (46, 'suspendisse', 'dog', 'Poodle', '2022/02/14');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (47, 'curabitur', 'dog', 'Labrador', '2022/03/18');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (48, 'nulla', 'cat', 'Persa', '2022/08/10');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (49, 'platea', 'cat', 'Persa', '2022/05/17');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (50, 'massa', 'cat', 'Ragdoll', '2022/03/24');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (51, 'erat', 'dog', 'Labrador', '2022/01/25');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (52, 'sit', 'cat', 'Siames', '2022/04/29');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (53, 'dis', 'dog', 'Poodle', '2022/07/07');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (54, 'felis', 'dog', 'Dachshund', '2022/07/30');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (55, 'amet', 'dog', 'Dachshund', '2021/12/15');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (56, 'orci', 'cat', 'Red Point', '2021/09/25');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (57, 'mauris', 'dog', 'Labrador', '2022/07/30');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (58, 'dictumst', 'cat', 'Persa', '2021/10/29');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (59, 'in', 'dog', 'Chihuahua', '2022/04/25');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (60, 'at', 'cat', 'Red Point', '2022/07/19');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (61, 'consequat', 'dog', 'Vira Lata', '2022/06/11');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (62, 'rutrum', 'cat', 'Persa', '2022/04/15');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (63, 'ac', 'cat', 'Siames', '2022/02/26');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (64, 'lectus', 'dog', 'Labrador', '2021/12/30');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (65, 'nibh', 'cat', 'Vira Lata', '2022/05/24');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (66, 'erat', 'dog', 'Akita', '2022/06/27');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (67, 'viverra', 'cat', 'Ragdoll', '2022/01/03');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (68, 'porta', 'dog', 'Dachshund', '2022/05/15');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (69, 'vestibulum', 'cat', 'Raggamuffin', '2022/04/10');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (70, 'posuere', 'dog', 'Dachshund', '2022/07/08');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (71, 'ut', 'dog', 'Dachshund', '2022/07/30');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (72, 'tempus', 'cat', 'Raggamuffin', '2022/06/03');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (73, 'purus', 'cat', 'Persa', '2021/12/16');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (74, 'odio', 'cat', 'Raggamuffin', '2022/05/29');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (75, 'quam', 'dog', 'Akita', '2022/06/17');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (76, 'platea', 'dog', 'Akita', '2022/04/13');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (77, 'fermentum', 'dog', 'Akita', '2022/04/30');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (78, 'orci', 'dog', 'Dachshund', '2022/04/22');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (79, 'ultricies', 'cat', 'Ragdoll', '2022/01/10');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (80, 'vehicula', 'dog', 'Vira Lata', '2022/06/25');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (81, 'sed', 'dog', 'Vira Lata', '2022/02/22');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (82, 'scelerisque', 'dog', 'Akita', '2022/01/09');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (83, 'eget', 'cat', 'Persa', '2021/11/24');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (84, 'odio', 'cat', 'Raggamuffin', '2021/11/22');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (85, 'amet', 'dog', 'Poodle', '2022/04/27');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (86, 'id', 'dog', 'Vira Lata', '2022/03/09');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (87, 'in', 'dog', 'Chihuahua', '2022/05/02');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (88, 'id', 'cat', 'Siames', '2022/08/17');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (89, 'vulputate', 'dog', 'Vira Lata', '2021/10/20');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (90, 'duis', 'cat', 'Raggamuffin', '2021/12/05');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (91, 'sapien', 'dog', 'Akita', '2022/06/03');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (92, 'ipsum', 'cat', 'Raggamuffin', '2021/12/06');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (93, 'aliquam', 'cat', 'Raggamuffin', '2022/06/01');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (94, 'vivamus', 'dog', 'Chihuahua', '2022/08/05');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (95, 'nisi', 'cat', 'Vira Lata', '2022/01/25');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (96, 'diam', 'dog', 'Labrador', '2021/10/15');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (97, 'viverra', 'dog', 'Poodle', '2022/03/11');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (98, 'nibh', 'cat', 'Raggamuffin', '2021/11/04');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (99, 'vitae', 'cat', 'Siames', '2022/02/05');
INSERT INTO pet (id_pet, name, type, race, createdAt) VALUES (100, 'odio', 'dog', 'Vira Lata', '2022/07/21');

SELECT *
FROM pet;

